const getUserData=async(req,res)=>{
    try {
        
    } catch (error) {
        
    }
}